name: main
on: push
jobs:
  run-test:
    runs-on: Windows-latest
    steps:
run-name: Checkout code
        uses: actions/checkout@v2
        run: echo "Running simple test1"
        
        

  second-stage:
    runs-on: ubuntu-latest
    needs: first-stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run second stage
        run: echo "Second stage completed"


